class Routes {
	HOME = "/"
	
	LOGIN = "/login"
	FORGOT_PASSWORD = "/forgot-password"
	REGISTER = "/register"
	
	DASHBOARD_GROUP = "#Dashboard"
	DASHBOARD = "/dashboard"
	DASHBOARD_DEFAULT = "/dashboard"
	DASHBOARD_ANALYTICS = "/dashboard/analytics"
	DASHBOARD_INVOICE = "/dashboard/invoice"
	COMPONENTS = "/components"
	
	WIDGETS_GROUP = "#Widgets"
	WIDGETS_STATISTICS = "/widgets/statistics"
	WIDGETS_DATA = "/widgets/data"
	WIDGETS_CHART = "/widgets/chart"
	
	APPS_GROUP = "#Apps"
	APPS_CHAT = "/apps/chat"
	APPS_CALENDAR = "/apps/calendar"
	APPS_KANBAN = "/apps/kanban"
	APPS_CUSTOMER = "/apps/customer"
	APPS_CUSTOMER_LIST = "/apps/customer/list"
	APPS_CUSTOMER_CARD = "/apps/customer/card"
	APPS_INVOICE = "/apps/invoice/dashboard"
	APPS_INVOICE_CREATE = "/apps/invoice/create"
	APPS_INVOICE_DETAILS_1 = "/apps/invoice/details/1"
	APPS_INVOICE_LIST = "/apps/invoice/list"
	APPS_INVOICE_EDIT_1 = "/apps/invoice/edit/1"
	APPS_PROFILE = "/apps/profile"
	APPS_PROFILE_USER = "/apps/profile/user"
	APPS_PROFILE_ACCOUNT = "/apps/profile/account"
	APPS_E_COMMERCE = "/apps/e-commerce"
	APPS_E_COMMERCE_PRODUCTS = "/apps/e-commerce/products"
	APPS_E_COMMERCE_PRODUCT_DETAIL_1 = "/apps/e-commerce/product-details/1"
	APPS_E_COMMERCE_PRODUCT_LIST = "/apps/e-commerce/product-list"
	APPS_E_COMMERCE_ADD_NEW_PRODUCT = "/apps/e-commerce/add-new-product"
	APPS_E_COMMERCE_CHECKOUT = "/apps/e-commerce/checkout"
	
	FORMS_AND_TABLES_GROUP = "#Forms"
	FORMS_AND_TABLES_VALIDATION = "/forms/validation"
	FORMS_AND_TABLES_WIZARD = "/forms/wizard"
	FORMS_AND_TABLES_LAYOUT = "/forms/layout"
	FORMS_AND_TABLES_LAYOUT_BASIC = "/forms/layout/basic"
	FORMS_AND_TABLES_LAYOUT_MULTI_COLUMN = "/forms/layout/multi-column"
	FORMS_AND_TABLES_LAYOUT_ACTION_BAR = "/forms/layout/action-bar"
	FORMS_AND_TABLES_LAYOUT_STICKY_BAR = "/forms/layout/sticky-bar"
	FORMS_AND_TABLES_PLUGINS = "/forms/plugins"
	FORMS_AND_TABLES_PLUGINS_MASK = "/forms/plugins/mask"
	FORMS_AND_TABLES_PLUGINS_CLIPBOARD = "/forms/plugins/clipboard"
	FORMS_AND_TABLES_PLUGINS_RE_CAPTCHA = "/forms/plugins/re-captcha"
	FORMS_AND_TABLES_PLUGINS_EDITOR = "/forms/plugins/editor"
	FORMS_AND_TABLES_PLUGINS_DROPZONE = "/forms/plugins/dropzone"
}

export const ROUTES = new Routes()
