class Routes {
	HOME = "/"
	
	LOGIN = "/login"
	LOGOUT = "/logout"
	FORGOT_PASSWORD = "/forgot-password"
	REGISTER = "/register"
	
	DASHBOARD_GROUP = "#Dashboard"
	DASHBOARD = "/dashboard"
	DASHBOARD_DEFAULT = "/dashboard/default"
	DASHBOARD_ANALYTICS = "/dashboard/analytics"
	DASHBOARD_INVOICE = "/dashboard/invoice"
	COMPONENTS = "/components"
	
	WIDGETS_GROUP = "#Widgets"
	WIDGETS_STATISTICS = "/widgets/statistics"
	WIDGETS_DATA = "/widgets/data"
	WIDGETS_CHART = "/widgets/chart"
	
	APPS_GROUP = "#Apps"
	APPS_CHAT = "/apps/chat"
	APPS_CALENDAR = "/apps/calendar"
	APPS_KANBAN = "/apps/kanban"
	APPS_CUSTOMER = "/apps/customer"
	APPS_CUSTOMER_LIST = "/apps/customer/list"
	APPS_CUSTOMER_CARD = "/apps/customer/card"
	APPS_INVOICE = "/apps/invoice/dashboard"
	APPS_INVOICE_CREATE = "/apps/invoice/create"
	APPS_INVOICE_DETAILS_1 = "/apps/invoice/details/1"
	APPS_INVOICE_LIST = "/apps/invoice/list"
	APPS_INVOICE_EDIT_1 = "/apps/invoice/edit/1"
	APPS_PROFILE = "/apps/profile"
	APPS_PROFILE_USER = "/apps/profile/user"
	APPS_PROFILE_ACCOUNT = "/apps/profile/account"
	APPS_E_COMMERCE = "/apps/e-commerce"
	APPS_E_COMMERCE_PRODUCTS = "/apps/e-commerce/products"
	APPS_E_COMMERCE_PRODUCT_DETAIL_1 = "/apps/e-commerce/product-details/1"
	APPS_E_COMMERCE_PRODUCT_LIST = "/apps/e-commerce/product-list"
	APPS_E_COMMERCE_ADD_NEW_PRODUCT = "/apps/e-commerce/add-new-product"
	APPS_E_COMMERCE_CHECKOUT = "/apps/e-commerce/checkout"
	
	FORMS_AND_TABLES_GROUP = "#Forms"
	FORMS_AND_TABLES_VALIDATION = "/forms/validation"
	FORMS_AND_TABLES_WIZARD = "/forms/wizard"
	FORMS_AND_TABLES_LAYOUT = "/forms/layout"
	FORMS_AND_TABLES_LAYOUT_BASIC = "/forms/layout/basic"
	FORMS_AND_TABLES_LAYOUT_MULTI_COLUMN = "/forms/layout/multi-column"
	FORMS_AND_TABLES_LAYOUT_ACTION_BAR = "/forms/layout/action-bar"
	FORMS_AND_TABLES_LAYOUT_STICKY_BAR = "/forms/layout/sticky-bar"
	FORMS_AND_TABLES_PLUGINS = "/forms/plugins"
	FORMS_AND_TABLES_PLUGINS_MASK = "/forms/plugins/mask"
	FORMS_AND_TABLES_PLUGINS_CLIPBOARD = "/forms/plugins/clipboard"
	FORMS_AND_TABLES_PLUGINS_RE_CAPTCHA = "/forms/plugins/re-captcha"
	FORMS_AND_TABLES_PLUGINS_EDITOR = "/forms/plugins/editor"
	FORMS_AND_TABLES_PLUGINS_DROPZONE = "/forms/plugins/dropzone"
	
	FORMS_AND_TABLES_TABLE = "/tables/table"
	FORMS_AND_TABLES_TABLE_BASIC = "/tables/table/basic"
	FORMS_AND_TABLES_TABLE_DENSE = "/tables/table/dense"
	FORMS_AND_TABLES_TABLE_SORTING = "/tables/table/sorting"
	FORMS_AND_TABLES_TABLE_FILTERING = "/tables/table/filtering"
	FORMS_AND_TABLES_TABLE_GROUPING = "/tables/table/grouping"
	FORMS_AND_TABLES_TABLE_PAGINATION = "/tables/table/pagination"
	FORMS_AND_TABLES_TABLE_ROW_SELECTION = "/tables/table/row-selection"
	FORMS_AND_TABLES_TABLE_EXPANDING = "/tables/table/expanding"
	FORMS_AND_TABLES_TABLE_EDITABLE = "/tables/table/editable"
	FORMS_AND_TABLES_TABLE_DRAG_AND_DROP = "/tables/table/drag-drop"
	FORMS_AND_TABLES_TABLE_COLUMN_VISIBILITY = "/tables/table/column-visibility"
	FORMS_AND_TABLES_TABLE_COLUMN_RESIZING = "/tables/table/column-resizing"
	FORMS_AND_TABLES_TABLE_STICKY = "/tables/table/sticky"
	FORMS_AND_TABLES_TABLE_UMBRELLA = "/tables/table/umbrella"
	FORMS_AND_TABLES_TABLE_EMPTY = "/tables/table/empty"
	FORMS_AND_TABLES_TABLE_VIRTUALIZED = "/tables/table/virtualized"
	
	CHARTS_AND_MAP_GROUP = "#Charts&Map"
	CHARTS_AND_MAP_CHARTS = "/charts"
	CHARTS_AND_MAP_CHARTS_ECHARTS = "/charts/echarts"
	CHARTS_AND_MAP_CHARTS_ORGANIZATION_CHART = "/charts/org-chart"
	CHARTS_AND_MAP_MAP = "/map"
	
	SAMPLE_PAGE = "/sample-page"
	
	PAGES_GROUP = "#Pages"
	PAGES_AUTHENTICATION = "/auth"
	PAGES_AUTHENTICATION_LOGIN = "/auth/login"
	PAGES_AUTHENTICATION_REGISTER = "/auth/register"
	PAGES_AUTHENTICATION_FORGOT_PASSWORD = "/auth/forgot-password"
	PAGES_AUTHENTICATION_RESET_PASSWORD = "/auth/reset-password"
	PAGES_AUTHENTICATION_CHECK_MAIL = "/auth/check-mail"
	PAGES_AUTHENTICATION_CODE_VERIFICATION = "/auth/code-verification"
	PAGES_MAINTENANCE = "/maintenance"
	PAGES_MAINTENANCE_404 = "/maintenance/404"
	PAGES_MAINTENANCE_500 = "/maintenance/500"
	PAGES_MAINTENANCE_COMING_SOON = "/maintenance/coming-soon"
	PAGES_MAINTENANCE_UNDER_CONSTRUCTION = "/maintenance/under-construction"
	PAGES_CONTACT_US = "/contact-us"
	PAGES_PRICING = "/pricing"
	
	MENU_LEVELS = "/menu-levels"
	MENU_LEVELS_LEVEL1 = "/menu-levels/level-1"
	MENU_LEVELS_LEVEL2 = "/menu-levels/level-1/level-2"
	MENU_LEVELS_LEVEL3 = "/menu-levels/level-1/level-2/level-3"
	
	SUB_CAPTION_LEVELS = "/sub-caption-levels"
	SUB_CAPTION_LEVELS_LEVEL1 = "/sub-caption-levels/level-1"
	SUB_CAPTION_LEVELS_LEVEL2 = "/sub-caption-levels/level-1/level-2"
	
	DISABLED_MENU = "/disabled-menu"
	OVAL_CHIP = "/oval-chip"
	DOCUMENTATION = "/documentation"
	ROADMAP = "/roadmap"
	
	NOT_FOUND = "/*"
}

export const ROUTES = new Routes()
